CREATE TABLE starter_health (id text PRIMARY KEY);
CREATE TABLE "user" (id text PRIMARY KEY, name text NOT NULL, email text NOT NULL UNIQUE, email_verified boolean NOT NULL DEFAULT false, two_factor_enabled boolean DEFAULT false, image text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE "session" (id text PRIMARY KEY, expires_at timestamptz NOT NULL, token text NOT NULL UNIQUE, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), ip_address text, user_agent text, user_id text NOT NULL REFERENCES "user"(id) ON DELETE CASCADE);
CREATE INDEX session_user_id_idx ON "session" (user_id);
CREATE TABLE "account" (id text PRIMARY KEY, issuer text NOT NULL, account_id text NOT NULL, provider_id text NOT NULL, user_id text NOT NULL REFERENCES "user"(id) ON DELETE CASCADE, access_token text, refresh_token text, id_token text, access_token_expires_at timestamptz, refresh_token_expires_at timestamptz, scope text, password text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (issuer, account_id));
CREATE INDEX account_user_id_idx ON "account" (user_id);
CREATE TABLE "verification" (id text PRIMARY KEY, identifier text NOT NULL, value text NOT NULL, expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX verification_identifier_idx ON "verification" (identifier);
CREATE TABLE "two_factor" (id text PRIMARY KEY, user_id text NOT NULL REFERENCES "user"(id) ON DELETE CASCADE, secret text NOT NULL, backup_codes text NOT NULL, verified boolean NOT NULL DEFAULT false, failed_verification_count integer NOT NULL DEFAULT 0, locked_until timestamptz);
CREATE TABLE "passkey" (id text PRIMARY KEY, name text, public_key text NOT NULL, user_id text NOT NULL REFERENCES "user"(id) ON DELETE CASCADE, credential_id text NOT NULL UNIQUE, counter integer NOT NULL, device_type text NOT NULL, backed_up boolean NOT NULL, transports text, created_at timestamptz DEFAULT now(), aaguid text);
CREATE TABLE authentication_assurance (session_token text PRIMARY KEY REFERENCES "session"(token) ON DELETE CASCADE, assurance text NOT NULL CHECK (assurance IN ('single_factor', 'multi_factor', 'phishing_resistant', 'recovery')), authenticated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE application_users (id text PRIMARY KEY, authentication_subject_id text NOT NULL UNIQUE);
CREATE TABLE organizations (id text PRIMARY KEY, name text NOT NULL, created_by_subject_id text NOT NULL REFERENCES application_users(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE memberships (id text PRIMARY KEY, user_id text NOT NULL REFERENCES application_users(id), organization_id text NOT NULL REFERENCES organizations(id), status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (organization_id, user_id), UNIQUE (id, organization_id));
CREATE TABLE governance_role_assignments (id text PRIMARY KEY, membership_id text NOT NULL UNIQUE REFERENCES memberships(id) ON DELETE CASCADE, organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, role text NOT NULL CHECK (role IN ('owner', 'admin', 'member')), granted_by_subject_id text NOT NULL REFERENCES application_users(id), created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY (membership_id, organization_id) REFERENCES memberships(id, organization_id));
CREATE TABLE product_role_assignments (id text PRIMARY KEY, membership_id text NOT NULL REFERENCES memberships(id) ON DELETE CASCADE, organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, role text NOT NULL, granted_by_subject_id text NOT NULL REFERENCES application_users(id), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (membership_id, role), FOREIGN KEY (membership_id, organization_id) REFERENCES memberships(id, organization_id));
CREATE TABLE permission_definitions (id text PRIMARY KEY, permission text NOT NULL UNIQUE);
CREATE TABLE permission_grants (id text PRIMARY KEY, membership_id text NOT NULL REFERENCES memberships(id) ON DELETE CASCADE, organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, permission_id text NOT NULL REFERENCES permission_definitions(id), granted_by_subject_id text NOT NULL REFERENCES application_users(id), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (membership_id, permission_id), FOREIGN KEY (membership_id, organization_id) REFERENCES memberships(id, organization_id));
CREATE TABLE invitations (id text PRIMARY KEY, organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, email text NOT NULL, token_hash text NOT NULL UNIQUE, governance_role text NOT NULL CHECK (governance_role IN ('owner', 'admin', 'member')), product_roles text[] NOT NULL DEFAULT '{}', status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'revoked', 'expired')), expires_at timestamptz NOT NULL, accepted_at timestamptz, revoked_at timestamptz, invited_by_subject_id text NOT NULL REFERENCES application_users(id), created_at timestamptz NOT NULL DEFAULT now(), CHECK ((status = 'accepted') = (accepted_at IS NOT NULL)), CHECK ((status = 'revoked') = (revoked_at IS NOT NULL)));
CREATE TABLE authorization_audit_events (id text PRIMARY KEY, organization_id text NOT NULL REFERENCES organizations(id), actor_subject_id text NOT NULL REFERENCES application_users(id), action text NOT NULL, resource_type text NOT NULL, resource_id text, outcome text NOT NULL CHECK (outcome IN ('allowed', 'denied')), correlation_id text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE OR REPLACE FUNCTION app_current_organization_id() RETURNS text LANGUAGE sql STABLE AS $$ SELECT NULLIF(current_setting('app.organization_id', true), '') $$;
CREATE OR REPLACE FUNCTION app_current_subject_id() RETURNS text LANGUAGE sql STABLE AS $$ SELECT NULLIF(current_setting('app.subject_id', true), '') $$;
CREATE OR REPLACE FUNCTION protect_last_organization_owner() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF OLD.role = 'owner' AND (TG_OP = 'DELETE' OR NEW.role <> 'owner') AND NOT EXISTS (SELECT 1 FROM governance_role_assignments role_assignment JOIN memberships membership ON membership.id = role_assignment.membership_id WHERE role_assignment.organization_id = OLD.organization_id AND role_assignment.membership_id <> OLD.membership_id AND role_assignment.role = 'owner' AND membership.status = 'active') THEN RAISE EXCEPTION 'organization must retain an active owner'; END IF; RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END; END $$;
CREATE TRIGGER governance_role_last_owner BEFORE UPDATE OR DELETE ON governance_role_assignments FOR EACH ROW EXECUTE FUNCTION protect_last_organization_owner();
ALTER TABLE organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE organizations FORCE ROW LEVEL SECURITY;
CREATE POLICY organizations_tenant_isolation ON organizations USING (id = app_current_organization_id()) WITH CHECK (id = app_current_organization_id());
ALTER TABLE memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE memberships FORCE ROW LEVEL SECURITY;
CREATE POLICY memberships_tenant_isolation ON memberships USING (organization_id = app_current_organization_id()) WITH CHECK (organization_id = app_current_organization_id());
ALTER TABLE governance_role_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE governance_role_assignments FORCE ROW LEVEL SECURITY;
CREATE POLICY governance_role_assignments_tenant_isolation ON governance_role_assignments USING (organization_id = app_current_organization_id()) WITH CHECK (organization_id = app_current_organization_id());
ALTER TABLE product_role_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_role_assignments FORCE ROW LEVEL SECURITY;
CREATE POLICY product_role_assignments_tenant_isolation ON product_role_assignments USING (organization_id = app_current_organization_id()) WITH CHECK (organization_id = app_current_organization_id());
ALTER TABLE permission_grants ENABLE ROW LEVEL SECURITY;
ALTER TABLE permission_grants FORCE ROW LEVEL SECURITY;
CREATE POLICY permission_grants_tenant_isolation ON permission_grants USING (organization_id = app_current_organization_id()) WITH CHECK (organization_id = app_current_organization_id());
ALTER TABLE invitations ENABLE ROW LEVEL SECURITY;
ALTER TABLE invitations FORCE ROW LEVEL SECURITY;
CREATE POLICY invitations_tenant_isolation ON invitations USING (organization_id = app_current_organization_id()) WITH CHECK (organization_id = app_current_organization_id());
ALTER TABLE authorization_audit_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE authorization_audit_events FORCE ROW LEVEL SECURITY;
CREATE POLICY authorization_audit_events_tenant_isolation ON authorization_audit_events USING (organization_id = app_current_organization_id()) WITH CHECK (organization_id = app_current_organization_id());
CREATE TABLE workflow_runs (idempotency_key text PRIMARY KEY, status text NOT NULL, claim_token text NOT NULL, claim_expires_at timestamptz NOT NULL);
CREATE TABLE outbox_events (id text PRIMARY KEY, organization_id text, type text NOT NULL, schema_version integer NOT NULL CHECK (schema_version > 0), aggregate_type text NOT NULL, aggregate_id text NOT NULL, payload jsonb NOT NULL, destination text NOT NULL, idempotency_key text NOT NULL, status text NOT NULL DEFAULT 'available' CHECK (status IN ('available', 'processing', 'delivered', 'dead_letter')), available_at timestamptz NOT NULL DEFAULT now(), attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0), lease_owner text, lease_expires_at timestamptz, fencing_token bigint NOT NULL DEFAULT 0, correlation_id text NOT NULL, causation_id text, occurred_at timestamptz NOT NULL, last_failure text, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (destination, idempotency_key));
CREATE INDEX outbox_events_claim_idx ON outbox_events (status, available_at, lease_expires_at);
CREATE TABLE outbox_delivery_attempts (id text PRIMARY KEY, event_id text NOT NULL REFERENCES outbox_events(id) ON DELETE CASCADE, attempt_number integer NOT NULL CHECK (attempt_number > 0), fencing_token bigint NOT NULL, outcome text NOT NULL CHECK (outcome IN ('delivered', 'retry', 'dead_letter')), normalized_failure text, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (event_id, attempt_number));
CREATE TABLE outbox_dead_letters (event_id text PRIMARY KEY REFERENCES outbox_events(id) ON DELETE CASCADE, organization_id text, reason text NOT NULL, replayed_by_subject_id text, replayed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE inbox_receipts (id text PRIMARY KEY, organization_id text, consumer text NOT NULL, event_id text NOT NULL, idempotency_key text NOT NULL, processed_at timestamptz NOT NULL DEFAULT now(), UNIQUE (consumer, event_id), UNIQUE (consumer, idempotency_key));
ALTER TABLE outbox_events ADD CONSTRAINT outbox_events_organization_fk FOREIGN KEY (organization_id) REFERENCES organizations(id);
ALTER TABLE outbox_dead_letters ADD CONSTRAINT outbox_dead_letters_organization_fk FOREIGN KEY (organization_id) REFERENCES organizations(id);
ALTER TABLE inbox_receipts ADD CONSTRAINT inbox_receipts_organization_fk FOREIGN KEY (organization_id) REFERENCES organizations(id);
ALTER TABLE outbox_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE outbox_events FORCE ROW LEVEL SECURITY;
CREATE POLICY outbox_events_tenant_isolation ON outbox_events USING (organization_id IS NULL OR organization_id = app_current_organization_id()) WITH CHECK (organization_id IS NULL OR organization_id = app_current_organization_id());
ALTER TABLE outbox_dead_letters ENABLE ROW LEVEL SECURITY;
ALTER TABLE outbox_dead_letters FORCE ROW LEVEL SECURITY;
CREATE POLICY outbox_dead_letters_tenant_isolation ON outbox_dead_letters USING (organization_id IS NULL OR organization_id = app_current_organization_id()) WITH CHECK (organization_id IS NULL OR organization_id = app_current_organization_id());
ALTER TABLE inbox_receipts ENABLE ROW LEVEL SECURITY;
ALTER TABLE inbox_receipts FORCE ROW LEVEL SECURITY;
CREATE POLICY inbox_receipts_tenant_isolation ON inbox_receipts USING (organization_id IS NULL OR organization_id = app_current_organization_id()) WITH CHECK (organization_id IS NULL OR organization_id = app_current_organization_id());
